### ISSUE TITLE
Improve password validation error feedback

### ISSUE THREAD

**Issue by jappareti** [pensieve-srs/pensieve-web#66]
It's not clear which part of the validation for the password is failing when you enter an invalid password on the signup form. For instance, if you don't enter a number, there should be an error message that says you still need a number. Currently, the only error message is: "Short passwords are easy to guess. Try one with at least 8 characters."

I think each password rule should be validated individually with an indication that the password passes the checks. Maybe add a tooltip next to the password input showing the validation checks.

**Comment by nlaz** [comment]
This is a good issue. This is where the password is validated on the frontend: https://github.com/pensieve-srs/pensieve-web/blob/master/src/app/auth/Login.js#L74-L79 and https://github.com/pensieve-srs/pensieve-web/blob/master/src/app/auth/Signup.js#L97-L102.

You are welcome to tackle it if you like.

**Comment by jappareti** [comment]
Ok great I'll take a look.
